REM <PRE>
REM SCHEMA TK_OPHA

 
 CREATE TABLE ARVOSANA(
 ARVOSANA                        VARCHAR2(2) NOT NULL
,PRIMARY KEY (ARVOSANA));
 
CREATE TABLE ARVTAPA(
  TAPA                                     CHAR(1)
, SELITYS                                  VARCHAR2(48)
,PRIMARY KEY (TAPA)
);

CREATE TABLE ENTINEN_OPETUS(
 LUKUKAUSI                       VARCHAR2(4)
,SIS_TUNNUS                      NUMBER(22)
,KURSSIKOODI                     VARCHAR2(10)
,NIMI                            VARCHAR2(80)
,TYYPPI                          VARCHAR2(1)
,LUKUVUOSI                       NUMBER(22)
);
 
CREATE TABLE ENTISET_ILM(
 SOTU                            VARCHAR2(10) NOT NULL
,LUKUKAUSI                       VARCHAR2(4) NOT NULL
,KOHDE                           NUMBER(22) NOT NULL
,KTYYPPI                         VARCHAR2(1)
,VOIMASSA                        VARCHAR2(1)
,PVM                             DATE
,PAAKOHDE                        NUMBER(22)
,KELLO                           NUMBER(22)
,LUKUVUOSI                       NUMBER(22)
,KURSSIKOODI                     VARCHAR2(11)
);

CREATE TABLE HENKILO(
 HTUNNUS                         VARCHAR2(12) NOT NULL
,ETUNIMET                        VARCHAR2(80) NOT NULL
,SUKUNIMI                        VARCHAR2(80) NOT NULL
,KUTSUMANIMI                     VARCHAR2(15)
,AKTIIVISUUS                     VARCHAR2(1)
,HUONE_NRO                       VARCHAR2(5)
,HETU                            VARCHAR2(11)
,OPPIARVO                        VARCHAR2(5)
,TITTELI                         VARCHAR2(80)
,PUHELIN_TYO                     VARCHAR2(20)
,PUHELIN_KOTI                    VARCHAR2(20)
,KATUOSOITE                      VARCHAR2(40)
,POSTINRO                        VARCHAR2(5)
,POSTITOIMIPAIKKA                VARCHAR2(20)
,VALVONTASALDO                   NUMBER(5,2)
,SAHKOPOSTIOSOITE                VARCHAR2(80)
,HALLINNOLLINEN_KOMMENTTI        VARCHAR2(80)
,OPISKELIJA_KOMMENTTI            VARCHAR2(80)
,KTUNNUS                         VARCHAR(12)
,PRIMARY KEY (HTUNNUS));

 
CREATE TABLE HALLINNOLLINEN_RYHMA(
 HALLINNOLLINEN_RYHMA            VARCHAR2(12) NOT NULL
,TULOSTUS_JARJESTYS              NUMBER(22)
,RYHMA_NIMIKE                    VARCHAR2(80)
,PRIMARY KEY (HALLINNOLLINEN_RYHMA));
 
CREATE TABLE HALLINNOLLINEN_TEHTAVA(
 TEHTAVATUNNUS                   VARCHAR2(12) NOT NULL
,NIMIKE                          VARCHAR2(80) NOT NULL
,OPETUSVELV_HUOJENNUS            NUMBER(22)
,TEHTAVAKUVAUS                   VARCHAR2(240)
,HALLINNOLLINEN_RYHMA            VARCHAR2(12)
,TULOSTUS_JARJESTYS              NUMBER(22)
,PRIMARY KEY (TEHTAVATUNNUS));
 
CREATE TABLE HALLINNOLLISEN_TEHTAVAN_HOITO(
 TEHTAVATUNNUS                   VARCHAR2(12) NOT NULL
,HTUNNUS                         VARCHAR2(12) NOT NULL
,ALKAMIS_PVM                     DATE NOT NULL
,PAATTYMIS_PVM                   DATE
,TUNTIMAARA                      NUMBER(22)
,KOMMENTTI                       VARCHAR2(240)
,PRIMARY KEY (HTUNNUS,TEHTAVATUNNUS,ALKAMIS_PVM));
 
 
CREATE TABLE HUONE(
 HUONE_NRO                       VARCHAR2(5) NOT NULL
,PAIKKA_LKM                      NUMBER(22)
,KOKO                            NUMBER(6,1)
,VARUSTELU                       VARCHAR2(240)
,KOMMENTTI                       VARCHAR2(240)
,PRIMARY KEY (HUONE_NRO));
 
CREATE TABLE ILMOKYSYMYS(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,KYSYMYS_NRO                     NUMBER(22) NOT NULL
,KYSYMYS                         VARCHAR2(490) NOT NULL
,LYHENNE                         VARCHAR2(20)
,KYSYMYSTYYPPI                   VARCHAR(16)
,VAIHTOEHDOT                     VARCHAR(1000)
,ESITYSTILA                      VARCHAR(2)
,PRIMARY KEY (KURSSIKOODI,KYSYMYS_NRO));
 
CREATE TABLE ILMOLUKUMAARAT(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(22) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(22) NOT NULL
,RYHMA_NRO                       NUMBER(22) NOT NULL
,LUKUMAARA                       NUMBER(22) NOT NULL
,PRIMARY KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO,RYHMA_NRO));
 
CREATE TABLE ILMOVASTAUS(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,KYSYMYS_NRO                     NUMBER(22) NOT NULL
,HETU                            VARCHAR2(11) NOT NULL
,VASTAUS                         VARCHAR2(2000) NOT NULL
,LUKUVUOSI                       NUMBER(4)
,LUKUKAUSI                       CHAR(1)
,PRIMARY KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,KYSYMYS_NRO,HETU));
 
CREATE TABLE KALUSTELAJI(
 KALUSTELAJI                     VARCHAR2(5) NOT NULL
,KALUSTETYYPPI                   VARCHAR2(50)
,PRIMARY KEY (KALUSTELAJI));
 
CREATE TABLE KALUSTUS(
 HUONE_NRO                       VARCHAR2(5) NOT NULL
,KALUSTELAJI                     VARCHAR2(5) NOT NULL
,LUKUMAARA                       NUMBER(22)
,HANKINTA_AIKA                   DATE
,HANKINTA_HINTA                  NUMBER(9,2)
,ARVO                            NUMBER(9,2)
,POISTETTU                       DATE
);
 
CREATE TABLE KERROIN(
 VIRKA                           VARCHAR2(20)
,OPETUSTEHTAVA                   VARCHAR2(20)
,KERROIN                         VARCHAR2(3)
,PRIMARY KEY (VIRKA,OPETUSTEHTAVA));
 
CREATE TABLE KIELIKOODI(
 KIELIKOODI                      VARCHAR2(1) NOT NULL
,KIELI                           VARCHAR2(10)
,PRIMARY KEY (KIELIKOODI));
 
CREATE TABLE KOKEEN_TYYPPI(
 TYYPPI                          VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (TYYPPI));
 

CREATE TABLE KOETILAISUUS(
 LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(22) NOT NULL
,KOETILAISUUS_NRO                NUMBER(22) NOT NULL
,TOIVOTTU_SALI                   VARCHAR2(12)
,KOE_PVM                         DATE
,ALKAMISAIKA                     DATE
,PAATTYMISAIKA                   DATE
,KOMMENTTI                       VARCHAR2(240)
,VARATTU                         VARCHAR2(1)
,TILA                            VARCHAR2(1)
,PRIMARY KEY (LUKUKAUSI,LUKUVUOSI,KOETILAISUUS_NRO));


CREATE TABLE KOE(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(22) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(22) NOT NULL
,KOE_NRO                         NUMBER(22) NOT NULL
,KOETILAISUUS_NRO                NUMBER(22)
,KOE_TYYPPI                      VARCHAR2(1) NOT NULL
,ILMOITTAUTUNEET_LKM             NUMBER(3)
,OSALLISTUNEET_LKM               NUMBER(3)
,HTUNNUS                         VARCHAR2(12)
,PRIMARY KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO,KOE_NRO));
 
 
CREATE TABLE KURSSI(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(4) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(2) NOT NULL
,KIELIKOODI                      VARCHAR2(1) NOT NULL
,NIMI                            VARCHAR2(80) NOT NULL
,OPINTOVIIKOT                    NUMBER(3,1) NOT NULL
,LUENTOTUNNIT                    NUMBER(3)
,LUENTOKERTA_LKM                 NUMBER(3)
,HARJOITUSTUNNIT                 NUMBER(3)
,LASKARIKERTA_LKM                NUMBER(2)
,LYHENNE                         VARCHAR2(12)  -- ei käytössä
,SALASANA                        VARCHAR2(30)  -- ei käytössä
,SUORITUS_PVM                    DATE
,TILA                            VARCHAR2(1)
,ALKAMIS_PVM                     DATE
,PAATTYMIS_PVM                   DATE
,PAIVITYS_PVM                    DATE
,MAX_OSALLISTUJA_LKM             NUMBER(3)
,LASKARITEHTAVA_LKM              VARCHAR2(54) -- piilotaulukko[18]: 99,99,.....,99
,PAKOLLISET_LASKARIKERTA_LKM     NUMBER(2)
,PAKOLLISET_LASKARITEHTAVA_LKM   NUMBER(3)
,MAX_LASKARIPISTEET              NUMBER(2)
,HYVAKSYTTY_LASKARILASNAOLO      VARCHAR2(54)
,LISAPISTEALARAJA                NUMBER(3)
,LISAPISTERAJAT                  VARCHAR2(240) -- piilotaulukko[60]: 999,999,... 
,LISAPISTEIDEN_ASKELKOKO         NUMBER(3,1)
,HARJOITUSTYO_LKM                NUMBER(2)
,PAKOLLISET_HARJOITUSTYO_LKM     NUMBER(2)
,HARJOITUSTYOPISTEET             NUMBER(2)
,MAX_HARJOITUSTYOPISTEET         VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,MIN_HARJOITUSTYOPISTEET         VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,MIN_HARJOITUSTYOPISTEET_SUMMA   NUMBER(3)
,HARJOITUSTYON_PISTERAJAT        VARCHAR2(240)  -- piilotaulukko[60]: 999,999,... 
,HARJOITUSTOIDEN_ASKELKOKO       NUMBER(4,1)
,VALIKOKEET_LKM                  NUMBER(2)
,PAKOLLISET_KOE_LKM              NUMBER(2)
,MAX_KOEPISTEET                  VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,MIN_KOEPISTEET                  VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,MIN_KOEPISTEET_SUMMA            NUMBER(3)
,MIN_YHTEISPISTEET               NUMBER(3)
,ARVOSTELUN_ASKELKOKO            NUMBER(4,1)
,ARVOSANARAJAT                   VARCHAR2(80)  -- piilotaulukko[5]: 999,999,... 
,ARVOSTELLAANKO                  VARCHAR2(1)
,KOKONAISTIEDOT                  VARCHAR2(200)
,KUVAUSTIETO1                    VARCHAR2(800)
,KUVAUSTIETO2                    VARCHAR2(800)
,KUVAUSTIETO3                    VARCHAR2(800)
,HAKUKYSYMYKSET                  VARCHAR2(1)
,SUUNNITTELUKOMMENTTI            VARCHAR2(240)
,OMISTAJA                        VARCHAR2(30)
,PERUTTAVISSA                    CHAR(1)
,LASKENTAKAAVA                   NUMBER(2)
,ARVOSTELU_PVM                   DATE
,SIIRTO_PVM                      DATE
,HT_LISAPISTEALARAJA             NUMBER(3)
,ARVOSTELIJA                     VARCHAR2(30)
,OPINTOVIIKOT_YLARAJA            NUMBER(4,1)
,OPINTOPISTEET_YLARAJA           NUMBER(4,1)
,OPINTOPISTEET                   NUMBER(4,1)
,PERIODI                         NUMBER(2)
,KOTISIVU                        VARCHAR(120)
,PERIODI2                        NUMBER(2)
,PRIMARY KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO));
 
CREATE TABLE KURSSIN_TILA(
 TILA                            VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (TILA));
 
CREATE TABLE KURSSIN_TYYPPI(
 TYYPPI                          VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (TYYPPI));
 
 
CREATE TABLE LABRATYO_TILA(
 LABRATYO_TILA                   VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
,pPRIMARY KEY (LABRATYO_TILA));
 
CREATE TABLE LAITOS(
 LYHENNE                         VARCHAR2(6)
,RAPNIMI                         VARCHAR2(40)
,VASTHLOMAIL                     VARCHAR2(40)
,PRIMARY KEY (LYHENNE));
 
CREATE TABLE LUKUKAUSI(
 LUKUKAUSI                       VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(10)
,ALKAMIS_PVM                     DATE
,PAATTYMIS_PVM                   DATE
,PRIMARY KEY (LUKUKAUSI)
);
 
 
CREATE TABLE OPETUS(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(22) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(22) NOT NULL
,RYHMA_NRO                       NUMBER(22) NOT NULL
,ILMO_JNRO                       NUMBER(22)
,ILMO                            VARCHAR2(1)
,OPETUSTEHTAVA                   VARCHAR2(3)
,ALKAMISAIKA                     DATE
,PAATTYMISAIKA                   DATE
,ALKAMIS_PVM                     DATE
,PAATTYMIS_PVM                   DATE
,MAX_OSALLISTUJA_LKM             NUMBER(3)
,ILMOITTAUTUNEIDEN_LKM           NUMBER(3)
,KUVAUSTIETO                     VARCHAR2(70)
,PRIMARY KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO,RYHMA_NRO));
 
CREATE TABLE OPETUSALA(
 OPETUSALA                       VARCHAR2(5) NOT NULL
,KUVAUS                          VARCHAR2(240)
,PRIMARY KEY (OPETUSALA));

CREATE TABLE OPETUSPAKLKKIOT (
 TASO                             NUMBER(2) NOT NULL
, ALKAEN                          DATE NOT NULL
, ASTI                            DATE NOT NULL
, PERUSPALKKA                     NUMBER(6,2)
, PRIMARY KEY (TASO, ALKAEN));
 
CREATE TABLE OPETUSTEHTAVA(
 TYYPPI                          VARCHAR2(3) NOT NULL
,KUVAUS                          VARCHAR2(60) NOT NULL
,PRIMARY KEY (TYYPPI));
 
CREATE TABLE OPETUSTEHTAVA_KERTOIMET (
  TEHTAVA                         VARCHAR2(4) NOT NULL
, KERROIN                         NUMBER(6,2) NOT NULL
, ALKAEN                          DATE NOT NULL
, ASTI                            DATE NOT NULL
, PRIMARY KEY (TEHTAVA, ALKAEN)
);

CREATE TABLE OPETUSTEHTAVAN_HOITO(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(4) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(2) NOT NULL
,RYHMA_NRO                       NUMBER(2) NOT NULL
,HTUNNUS                         VARCHAR2(12) NOT NULL
,OPETUSTEHTAVA                   VARCHAR2(3) NOT NULL
,ALKAMIS_PVM                     DATE
,PAATTYMIS_PVM                   DATE
,TUNTIMAARA                      NUMBER(6)
,VASTUUHENKILO                   NUMBER(1)
, TASO                                     NUMBER(2)
, KERROIN                                  NUMBER(6,2)
, MAKSUPERUSTE                             CHAR(1)
,PRIMARY KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,KURSSI_NRO,TYYPPI,RYHMA_NRO,HTUNNUS,OPETUSTEHTAVA));
 
CREATE TABLE OPINTOJAKSON_TASO(
 TASO                            VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (TASO));

 
CREATE TABLE OPINTOJAKSON_TYYPPI(
 TYYPPI                          VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (TYYPPI));


CREATE TABLE OPINTOJAKSO(
 KURSSIKOODI                     VARCHAR2(15) NOT NULL
,TULOSTUS_JARJESTYS              NUMBER(22)
,NIMI_SUOMI                      VARCHAR2(80)
,NIMI_RUOTSI                     VARCHAR2(80)
,NIMI_ENGLANTI                   VARCHAR2(80)
,OPINTOVIIKOT                    NUMBER(4,1)
,OPINTOVIIKOT_YLARAJA            NUMBER(4,1)
,TYYPPI                          VARCHAR2(1)
,TASO                            VARCHAR2(1)
,KUVAUS                          VARCHAR2(2000)
,TIIVISTELMA                     VARCHAR2(480)
,VALIKOKEET_LKM                  NUMBER(2)
,SUUNTAUTUMISVAIHTOEHTO          VARCHAR2(1)
,LUENTOTUNNIT                    NUMBER(3)
,LUENTOKERTA_LKM                 NUMBER(3)
,HARJOITUSTUNNIT                 NUMBER(3)
,HARJOITUSKERTA_LKM              NUMBER(3)
,VOIMASSAOLO_ALKAMIS_PVM         DATE
,VOIMASSAOLO_PAATTYMIS_PVM       DATE
,PAKOLLISUUS                     CHAR(1)
, OPINTOPISTEET                            NUMBER(4,1)
, OPINTOPISTEET_YLARAJA                    NUMBER(4,1)
,KOTISIVU varchar(120)
,ESITIEDOT char(1)
,OPPIMISTAVOITTEET varchar(240)
,PRIMARY KEY (KURSSIKOODI));
 
 
CREATE TABLE OPISKELIJA(
 PERSONID                        VARCHAR2(11)  -- hetu, voi puuttua
,ETUNIMI                         VARCHAR2(25) NOT NULL
,SUKUNIMI                        VARCHAR2(40) NOT NULL
,ENTINEN_SUKUNIMI                VARCHAR2(80)
,OSOITE                          VARCHAR2(50)
,PUHELIN                         VARCHAR2(40)
,SAHKOPOSTIOSOITE                VARCHAR2(50)
,PAA_AINE                        VARCHAR2(3)
,ALOITUSVUOSI                    NUMBER(4)
,KAYTTO_PVM                      DATE
,OPNRO                           VARCHAR2(15) -- opiskelijanumero, ei käytössä
,LUPA                            VARCHAR2(12) 
,VINKKI                          VARCHAR2(40) -- ei käytössä
,VARMENNE                        VARCHAR2(20) -- ei käytössä
,HETU                            VARCHAR(9) PRIMARY KEY);  -- opiskelijanumero
 
CREATE TABLE OPPIARVO(
 OPPIARVO                        VARCHAR2(5) NOT NULL
,KUVAUS                          VARCHAR2(80)
,KUVAUS_RUOTSI                   VARCHAR2(80)
,KUVAUS_ENGLANTI                 VARCHAR2(80)
,PRIMARY KEY (OPPIARVO));
 
CREATE TABLE OSALLISTUMINEN(
 PERSONID                        VARCHAR2(11) -- hetu, voi puuttua
,KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(22) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(22) NOT NULL
,RYHMA_NRO                       NUMBER(22) NOT NULL
,KOMMENTTI_1                     VARCHAR2(240)
,KOMMENTTI_2                     VARCHAR2(240)
,LASKARI_LASNAOLO_LKM            NUMBER(2)
,LASKARISUORITUKSET              VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,LASKARISUORITUKSET_SUMMA        NUMBER(3)
,LASKARIHYVITYS                  NUMBER(3)
,HARJOITUSTYO_LASNAOLO_LKM       NUMBER(2)
,HARJOITUSTYOPISTEET             VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,HARJOITUSTYO_SUMMA              NUMBER(3)
,HARJOITUSTYOHYVITYS             NUMBER(3)
,KOEPISTEET                      VARCHAR2(54)  -- piilotaulukko[18]: 99,99,.....,99
,KOEPISTEET_SUMMA                NUMBER(3)
,YHTEISPISTEET                   NUMBER(3)
,ARVOSANA                        VARCHAR2(2)
,ILMOITTAUTUMIS_PVM              DATE
,VOIMASSA                        VARCHAR2(1)
,VIIMEINEN_KASITTELY_PVM         DATE
,ILMO_JNRO                       NUMBER(2)
,JAASSA                          CHAR(1)
,LAAJUUS_OV                      number(4,1)
,LAAJUUS_OP                      number(4,1)
,HETU                            VARCHAR(9) NOT NULL PRIMARY KEY
,KYPSYYS_PVM                     DATE    -- jotain?
,TENTTIJA                        VARCHAR(200) -- kommentteja
,KIELIKOODI                      VARCHAR(2) -- suorituksen kieli
); 
 
CREATE TABLE PAA_AINE(
 PAA_AINE                        VARCHAR2(3) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (PAA_AINE));
 
 
CREATE TABLE PROJEKTIVIITE(
 PROJEKTIVIITE                   VARCHAR2(3) NOT NULL
,KUVAUS                          VARCHAR2(30)
,PRIMARY KEY (PROJEKTIVIITE));
 
CREATE TABLE PUHELIN_YLEISET(
 PAIKKA                          CHAR(5)
,TNRO                            NUMBER(22)
,TEKSTI                          CHAR(40)
);
 
CREATE TABLE RAPORTTI(
 RAP                             NUMBER(22)
,RNO                             NUMBER(22)
,RIVI                            VARCHAR2(160)
);
 
 
CREATE TABLE SALI(
 SALI_NRO                        VARCHAR2(12) NOT NULL
,KOKO                            NUMBER(22)
,VARUSTELU                       VARCHAR2(240)
,PRIMARY KEY (SALI_NRO));
 
REM  Tähän tauluu kirjataan salivaraukset joko koetiölaisuuksille tai
REM  opetustilaisuuksille. Opetustilaisuuteen viitataan sarakeyhdistelmällä
REM  KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO, RYHMA_NRO
REM  Opetuksen luonne selviää taulusta opetus.
REM  Koetilaisuuteen viitataan sarakkeella KOETILAISUUS_NRO.
REM  Alkamis- ja päättymispäivä kertovat milloin varaus on voimassa.
REM  Päiväykset voivat olla samat.
REM  
CREATE TABLE SALIVARAUS(
 VARAUS_NRO                      NUMBER(22) NOT NULL
,SALI_NRO                        VARCHAR2(12)
,KURSSIKOODI                     VARCHAR2(15)
,LUKUKAUSI                       VARCHAR2(1)
,LUKUVUOSI                       NUMBER(22)
,TYYPPI                          VARCHAR2(1)
,KURSSI_NRO                      NUMBER(22)
,RYHMA_NRO                       NUMBER(22)
,KOETILAISUUS_NRO                NUMBER(22)
,VIIKONPAIVA                     VARCHAR2(2)
,ALKAMIS_PVM                     DATE
,PAATTYMIS_PVM                   DATE
,ALKAMISAIKA                     NUMBER(22)
,PAATTYMISAIKA                   NUMBER(22)
,ESIINTYMISTIHEYS                NUMBER(22)
,JOKAPAIVA                       NUMBER(22)
,VIIKONLOPPU                     NUMBER(22)
,TARKOITUS                       VARCHAR2(80)
,KAYTTAJA                        VARCHAR2(80)
,MA                              NUMBER(22)
,TI                              NUMBER(22)
,KE                              NUMBER(22)
,TR                              NUMBER(22)
,PE                              NUMBER(22)
,LA                              NUMBER(22)
,SU                              NUMBER(22)
,VARAUS_PVM                      DATE
,PRIMARY KEY (VARAUS_NRO));
 
CREATE TABLE SUUNNITTELULUKUKAUSI(
 LUKUKAUSI                       VARCHAR2(1)
,LUKUVUOSI                       NUMBER(22)
);
 
CREATE TABLE SUUNTAUTUMISVAIHTOEHTO(
 SUUNTAUTUMISVAIHTOEHTO          VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
);
vanhatos 
 
CREATE TABLE VANHATOS(
 PERSONID                        VARCHAR2(11) 
,KURSSIKOODI                     VARCHAR2(15) NOT NULL
,LUKUKAUSI                       VARCHAR2(1) NOT NULL
,LUKUVUOSI                       NUMBER(22) NOT NULL
,TYYPPI                          VARCHAR2(1) NOT NULL
,KURSSI_NRO                      NUMBER(22) NOT NULL
,RYHMA_NRO                       NUMBER(22) NOT NULL
,KOMMENTTI_1                     VARCHAR2(240)
,KOMMENTTI_2                     VARCHAR2(240)
,LABRATYO_NRO                    VARCHAR2(6)
,LABRATYO_NIMI                   VARCHAR2(60)
,LABRATYO_TUNNIT                 NUMBER(22)
,LABRATYO_TILA                   VARCHAR2(1)
,LABRATYO_VALMISTUMIS_PVM        DATE
,LASKARI_LASNAOLO_LKM            NUMBER(22)
,LASKARISUORITUKSET              VARCHAR2(54)
,LASKARISUORITUKSET_SUMMA        NUMBER(22)
,LASKARIHYVITYS                  NUMBER(22)
,HARJOITUSTYO_LASNAOLO_LKM       NUMBER(22)
,HARJOITUSTYOPISTEET             VARCHAR2(54)
,HARJOITUSTYO_SUMMA              NUMBER(22)
,HARJOITUSTYOHYVITYS             NUMBER(22)
,KOEPISTEET                      VARCHAR2(54)
,KOEPISTEET_SUMMA                NUMBER(22)
,YHTEISPISTEET                   NUMBER(22)
,ARVOSANA                        VARCHAR2(2)
,ILMOITTAUTUMIS_PVM              DATE
,VOIMASSA                        VARCHAR2(1)
,AIHE                            VARCHAR2(80)
,TENTTIJA                        VARCHAR2(80)
,SUORITUSAIKA                    VARCHAR2(80)
,TUTKINTO                        VARCHAR2(80)
,VIIMEINEN_KASITTELY_PVM         DATE
,OMISTAJA                        VARCHAR2(30)
,ILMO_JNRO                       NUMBER(22)
,KYPSYYS_PVM                     DATE
,KYPSYYSPAIKKA                   VARCHAR2(40)
,KYPSYYS_MUUTA                   VARCHAR2(80)
,HETU                            VARCHAR(9)  -- opiskelijanumero
);
 
CREATE TABLE VARAUSTYYPPI(
 VARAUSTYYPPI                    NUMBER(22) NOT NULL
,JOKAPAIVA                       NUMBER(22) NOT NULL
,VIIKONLOPPU                     NUMBER(22) NOT NULL
,VIIKONPAIVA                     VARCHAR2(2) NOT NULL
,SELITYS                         VARCHAR2(50) NOT NULL
,VIIKONPAIVA_R                   VARCHAR2(3)
,VIIKONPAIVA_E                   VARCHAR2(3)
,SELITYS_R                       VARCHAR2(50)
,SELITYS_E                       VARCHAR2(50)
);
 
CREATE TABLE VASTAANOTTO(
 HTUNNUS                         VARCHAR2(12) NOT NULL
,VIIKONPAIVA                     VARCHAR2(2) NOT NULL
,ALKAMISAIKA                     DATE NOT NULL
,PAATTYMISAIKA                   DATE NOT NULL
,PAIKKA                          VARCHAR2(12) NOT NULL
,ALKAMIS_PVM                     DATE NOT NULL
,PAATTYMIS_PVM                   DATE
,KOMMENTTI                       VARCHAR2(240)
,PRIMARY KEY (HTUNNUS,VIIKONPAIVA,ALKAMIS_PVM,ALKAMISAIKA));
 
CREATE TABLE VASTAANOTTO_YLEISET(
 PAIKKA                          CHAR(5)
,TNRO                            NUMBER(22)
,TEKSTI                          VARCHAR2(80)
);
 
CREATE TABLE VIRANHOIDON_TYYPPI(
 TYYPPI                          VARCHAR2(12) NOT NULL
,KUVAUS                          VARCHAR2(60) NOT NULL
);
 
CREATE TABLE VIRANHOITO_HALTIJA(
 VIRKA_NRO                       NUMBER(22) NOT NULL
,HTUNNUS                         VARCHAR2(12) NOT NULL
,ALKAMIS_PVM                     DATE NOT NULL
,HOITO_TYYPPI                    VARCHAR2(12) NOT NULL
,PAATTYMIS_PVM                   DATE
,ETULIITE                        VARCHAR2(12)
,TILA                            VARCHAR2(1)
,KOMMENTTI                       VARCHAR2(240)
,OPETUSALA                       VARCHAR2(5)
,PRIMARY KEY (VIRKA_NRO,HTUNNUS,ALKAMIS_PVM,HOITO_TYYPPI));
 
CREATE TABLE VIRAN_ETULIITE(
 ETULIITE                        VARCHAR2(2) NOT NULL
,KUVAUS                          VARCHAR2(30)
);
 
CREATE TABLE VIRAN_LAATU(
 LAATU                           VARCHAR2(12) NOT NULL
,KUVAUS                          VARCHAR2(60) NOT NULL
);
 
CREATE TABLE VIRAN_TILA(
 TILA                            VARCHAR2(1) NOT NULL
,KUVAUS                          VARCHAR2(30)
);
 
CREATE TABLE VIRKA(
 VIRKA_NRO                       NUMBER(22) NOT NULL
,TULOSTUS_JARJESTYS              NUMBER(22) NOT NULL
,NIMIKE                          VARCHAR2(80) NOT NULL
,NIMIKELYHENNE                   VARCHAR2(10) NOT NULL
,PALKKAUSLUOKKA                  VARCHAR2(12)
,LAATU                           VARCHAR2(12)
,PERUSTAMIS_PVM                  DATE
,LAKKAUTTAMIS_PVM                DATE
,PROJEKTIVIITE                   VARCHAR2(3)
,KOMMENTTI                       VARCHAR2(240)
,NIMIKE_RUOTSI                   VARCHAR2(80)
,NIMIKELYHENNE_RUOTSI            VARCHAR2(10)
,NIMIKE_ENGLANTI                 VARCHAR2(80)
,NIMIKELYHENNE_ENGLANTI          VARCHAR2(10)
,OPETUSALA                       VARCHAR2(5)
,PRIMARY KEY (VIRKA_NRO));
 
CREATE TABLE VIRKAVAPAUDEN_SYY(
 SYY                             VARCHAR2(3) NOT NULL
,KUVAUS                          VARCHAR2(80)
);
 
CREATE TABLE VIRKAVAPAUS(
 VIRKA_NRO                       NUMBER(22) NOT NULL
,HTUNNUS                         VARCHAR2(12) NOT NULL
,ALKAMIS_PVM                     DATE NOT NULL
,PAATTYMIS_PVM                   DATE NOT NULL
,TILA                            VARCHAR2(1)
,LAATU                           VARCHAR2(3)
,PERUSTE                         VARCHAR2(240)
,PRIMARY KEY (HTUNNUS,VIRKA_NRO,ALKAMIS_PVM));
 
CREATE TABLE VUOSIVIIKKO(
 VUOSI                           NUMBER(22)
,VIIKKO                          NUMBER(22)
);
 
CREATE TABLE YHTEYSTIEDOT(
 HTUNNUS                         VARCHAR2(12) NOT NULL
,TYYPPI                          VARCHAR2(3) NOT NULL
,YHTEYSTIETO                     VARCHAR2(120)
,NAKYVYYS                        VARCHAR2(1)
,PRIMARY KEY (HTUNNUS,TYYPPI));
 
CREATE TABLE YHTEYSTYYPPI(
 TYYPPI                          VARCHAR2(3) NOT NULL
,KUVAUS                          VARCHAR2(15) NOT NULL
);
 
ALTER TABLE HALLINNOLLINEN_TEHTAVA
  ADD ( CONSTRAINT FK_HT_HR
 FOREIGN KEY (HALLINNOLLINEN_RYHMA) REFERENCES HALLINNOLLINEN_RYHMA);
 
ALTER TABLE HALLINNOLLISEN_TEHTAVAN_HOITO
  ADD ( CONSTRAINT FK_HTH_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
 
ALTER TABLE HALLINNOLLISEN_TEHTAVAN_HOITO
  ADD ( CONSTRAINT FK_HTH_HT
 FOREIGN KEY (TEHTAVATUNNUS) REFERENCES HALLINNOLLINEN_TEHTAVA);
 
ALTER TABLE HENKILO
  ADD ( CONSTRAINT FK_H_COPP
 FOREIGN KEY (OPPIARVO) REFERENCES OPPIARVO);
 
ALTER TABLE HENKILO
  ADD ( CONSTRAINT FK_H_HUONE
 FOREIGN KEY (HUONE_NRO) REFERENCES HUONE);
 
ALTER TABLE ILMOKYSYMYS
  ADD ( CONSTRAINT FK_IK_OJ
 FOREIGN KEY (KURSSIKOODI) REFERENCES OPINTOJAKSO);
 
ALTER TABLE ILMOLUKUMAARAT
  ADD ( CONSTRAINT FK_ILKM_O
 FOREIGN KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO,RYHMA_NRO) REFERENCES OPETUS);


ALTER TABLE ILMOVASTAUS
  ADD ( CONSTRAINT FK_IV_IK
 FOREIGN KEY (KURSSIKOODI,KYSYMYS_NRO) REFERENCES ILMOKYSYMYS);

ALTER TABLE ILMOVASTAUS
  ADD ( CONSTRAINT FK_IV_op
 FOREIGN KEY (HETU) REFERENCES OPISKELIJA);

 
ALTER TABLE KALUSTUS
  ADD ( CONSTRAINT FK_KALUSTUS_HUONE
 FOREIGN KEY (HUONE_NRO) REFERENCES HUONE);
 
ALTER TABLE KALUSTUS
  ADD ( CONSTRAINT FK_KALUSTUS_LAJI
 FOREIGN KEY (KALUSTELAJI) REFERENCES KALUSTELAJI);
 
ALTER TABLE KOE
  ADD ( CONSTRAINT FK_KOE_CKOT
 FOREIGN KEY (KOE_TYYPPI) REFERENCES KOKEEN_TYYPPI);
 
ALTER TABLE KOE
  ADD ( CONSTRAINT FK_KOE_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
 
ALTER TABLE KOE
  ADD ( CONSTRAINT FK_KOE_K
 FOREIGN KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO) REFERENCES KURSSI);
 
ALTER TABLE KOE
  ADD ( CONSTRAINT FK_KOE_KOE_T
 FOREIGN KEY (LUKUKAUSI,LUKUVUOSI,KOETILAISUUS_NRO) REFERENCES KOETILAISUUS);
 
ALTER TABLE KOETILAISUUS
  ADD ( CONSTRAINT FK_KOE_T_CLUK
 FOREIGN KEY (LUKUKAUSI) REFERENCES LUKUKAUSI);
 
ALTER TABLE KURSSI
  ADD ( CONSTRAINT FK_K_CKIE
 FOREIGN KEY (KIELIKOODI) REFERENCES KIELIKOODI);
 
ALTER TABLE KURSSI
  ADD ( CONSTRAINT FK_K_CKTI
 FOREIGN KEY (TILA) REFERENCES KURSSIN_TILA);
 
ALTER TABLE KURSSI
  ADD ( CONSTRAINT FK_K_CKUT
 FOREIGN KEY (TYYPPI) REFERENCES KURSSIN_TYYPPI);
 
ALTER TABLE KURSSI
  ADD ( CONSTRAINT FK_K_OJ
 FOREIGN KEY (KURSSIKOODI) REFERENCES OPINTOJAKSO);

ALTER TABLE KURSSI
  ADD ( CONSTRAINT FK_K_HENK
  FOREIGN KEY (OMISTAJA) REFERENCES HENKILO);


ALTER TABLE OPETUS
  ADD ( CONSTRAINT FK_O_K
 FOREIGN KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO) REFERENCES KURSSI);
 
ALTER TABLE OPETUSTEHTAVAN_HOITO
  ADD ( CONSTRAINT FK_OH_COPE
 FOREIGN KEY (OPETUSTEHTAVA) REFERENCES OPETUSTEHTAVA);
 
ALTER TABLE OPETUSTEHTAVAN_HOITO
  ADD ( CONSTRAINT FK_OH_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
 
ALTER TABLE OPETUSTEHTAVAN_HOITO
  ADD ( CONSTRAINT FK_OTH_O
 FOREIGN KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO,RYHMA_NRO) REFERENCES OPETUS);
 
ALTER TABLE OPINTOJAKSO
  ADD ( CONSTRAINT FK_OJ_COTA
 FOREIGN KEY (TASO) REFERENCES OPINTOJAKSON_TASO);
 
ALTER TABLE OPINTOJAKSO
  ADD ( CONSTRAINT FK_OJ_COTY
 FOREIGN KEY (TYYPPI) REFERENCES OPINTOJAKSON_TYYPPI);
 
ALTER TABLE OPINTOJAKSO
  ADD ( CONSTRAINT FK_OJ_CSUU
 FOREIGN KEY (SUUNTAUTUMISVAIHTOEHTO) REFERENCES SUUNTAUTUMISVAIHTOEHTO);
 
ALTER TABLE OPISKELIJA
  ADD ( CONSTRAINT FK_OPI_CPAA
 FOREIGN KEY (PAA_AINE) REFERENCES PAA_AINE);
 
ALTER TABLE OSALLISTUMINEN
  ADD ( CONSTRAINT FK_OS_O
 FOREIGN KEY (KURSSIKOODI,LUKUKAUSI,LUKUVUOSI,TYYPPI,KURSSI_NRO,RYHMA_NRO) REFERENCES OPETUS);
 
ALTER TABLE OSALLISTUMINEN
  ADD ( CONSTRAINT FK_OS_OP
 FOREIGN KEY (HETU) REFERENCES OPISKELIJA);
 
ALTER TABLE SALIVARAUS
  ADD ( CONSTRAINT FK_SALI_V_KOE_T
 FOREIGN KEY (LUKUKAUSI,LUKUVUOSI,KOETILAISUUS_NRO) REFERENCES KOETILAISUUS);
 
ALTER TABLE SALIVARAUS
  ADD ( CONSTRAINT FK_SALI_V_SALI
 FOREIGN KEY (SALI_NRO) REFERENCES SALI);
 
 
ALTER TABLE VASTAANOTTO
  ADD ( CONSTRAINT FK_VO_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
 
ALTER TABLE VIRANHOITO_HALTIJA
  ADD ( CONSTRAINT FK_VH_CVHT
 FOREIGN KEY (HOITO_TYYPPI) REFERENCES VIRANHOIDON_TYYPPI);
 
ALTER TABLE VIRANHOITO_HALTIJA
  ADD ( CONSTRAINT FK_VH_CVTI
 FOREIGN KEY (TILA) REFERENCES VIRAN_TILA);
 
ALTER TABLE VIRANHOITO_HALTIJA
  ADD ( CONSTRAINT FK_VH_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
 
ALTER TABLE VIRANHOITO_HALTIJA ADD ( CONSTRAINT FK_VH_OA
 FOREIGN KEY (OPETUSALA) REFERENCES OPETUSALA);

ALTER TABLE VIRANHOITO_HALTIJA
  ADD ( CONSTRAINT FK_VH_VIRKA
 FOREIGN KEY (VIRKA_NRO) REFERENCES VIRKA);
 
ALTER TABLE VIRKA
  ADD ( CONSTRAINT FK_VIRKA_CPRJ
 FOREIGN KEY (PROJEKTIVIITE) REFERENCES PROJEKTIVIITE);
 
ALTER TABLE VIRKA
  ADD ( CONSTRAINT FK_VIRKA_CVLAA
 FOREIGN KEY (LAATU) REFERENCES VIRAN_LAATU);
 
ALTER TABLE VIRKA
  ADD ( CONSTRAINT FK_V_OA
 FOREIGN KEY (OPETUSALA) REFERENCES OPETUSALA);
 
ALTER TABLE VIRKAVAPAUS
  ADD ( CONSTRAINT FK_VK_CVVS
 FOREIGN KEY (LAATU) REFERENCES VIRKAVAPAUDEN_SYY);
 
ALTER TABLE VIRKAVAPAUS
  ADD ( CONSTRAINT FK_VK_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
 
ALTER TABLE VIRKAVAPAUS
  ADD ( CONSTRAINT FK_VK_VIRKA
 FOREIGN KEY (VIRKA_NRO) REFERENCES VIRKA);
 
ALTER TABLE YHTEYSTIEDOT
  ADD ( CONSTRAINT FK_YT_CTYY
 FOREIGN KEY (TYYPPI) REFERENCES YHTEYSTYYPPI);
 
ALTER TABLE YHTEYSTIEDOT
  ADD ( CONSTRAINT FK_YT_H
 FOREIGN KEY (HTUNNUS) REFERENCES HENKILO);
REM </pre>
